project:
  type: website
  output-dir: "docs"

website:
  title: "Proyectos GIM"
  favicon: img/logos/favicon.ico
  reader-mode: true
  navbar: 
    background: primary
    search: true

  # comments: 
  #   hypothesis:
  #     theme: clean
  #     openSidebar: true

book:
  title: "Proyectos GIM"
  subtitle: "Repositorio de casos prácticos"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2022"
  output-file: "proyectos-gim"
  image: cover.png
  cover-image: img/logos/proyectos.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  # sidebar:
  #   logo: img/logos/aprendeconalf.png
  #   tools:
  #     - icon: house-fill
  #       href: https://aprendeconalf.es
  # open-graph: true
  # twitter-card: 
  #   site: "@aprendeconalf"
  chapters:
    - index.qmd
    - proyectos/demanda-electrica.qmd
    - proyectos/telefonia-movil.qmd
    - proyectos/convive.qmd
    - proyectos/calculo-simbolico.qmd
    
#bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme:
      dark: darkly
      light: flatly
    html-math-method: mathjax
    toc: true
  pdf:
    documentclass: scrreport
    papersize: a4
    template-partials:
      - before-body.tex
    titlegraphic: img/logos/proyectos.png
    institution: CEU San Pablo
    email: asalber@ceu.es
    web: https://aprendeconalf.es
    logo: img/logos/aprendeconalf.png
    include-in-header:
      - preamble.tex
      - macros.tex
    keep-tex: true
    #mainfont: TeX Gyre Termes
    #mainfontoptions:
    #  - Numbers=Lowercase
    #  - Numbers=Proportional    
    
  epub:
    cover-image: img/logos/proyectos.png



